# -*- mode: ruby -*-
# vi: set ft=ruby :
#Author : Santosh Patil
#Date : March 14 2016

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
config.env.enable #enable the plugin
config.vm.provision "file", source: "", destination: "/home/vagrant"
# Configure additional CPUs and Memory
  config.vm.provider "virtualbox" do |v|
      v.memory = 2048
      v.cpus = 2
  end

  #
  # Add the required puppet modules before provisioning is run by puppet
  #
  config.vm.provision :shell do |shell|
     shell.inline = "puppet module install puppetlabs-stdlib;
                     puppet module install puppetlabs-apt;
					 puppet module install maestrodev-wget;
					 puppet module install tracywebtech-pip;
                     puppet module install boundary-boundary;
                     puppet module install PppetLabs Apt;
                     puppet module install puppetlabs-java;
                     exit 0"
  end

  #
  # Use Puppet to provision the server
  #
  config.vm.provision "puppet" do |puppet|
    puppet.manifests_path = "manifests"
    puppet.manifest_file  = "site.pp"
    puppet.facter = {
      "boundary_api_token" => ENV["BOUNDARY_API_TOKEN"]
     
    }
  end

if ENV['OSTYPE'] == 'centos-6-6'
  config.vm.define "centos-6.6", autostart: true do |v|
    v.vm.box = "puppetlabs/centos-6.6-64-puppet"
    v.vm.box_version = "1.0.1"
    v.vm.hostname = "centos-6-6"
	
	# Needed to override to change the default outside-in ordering.
    config.vm.provision "puppet" do |puppet|
      puppet.manifests_path = "manifests"
      puppet.manifest_file  = "site.pp"
      puppet.facter = {
        "boundary_api_token" => ENV["BOUNDARY_API_TOKEN"]     
      }
    end
  end
end
  
#Ubuntu 12-04 Version
if ENV['OSTYPE'] == 'ubuntu-12-04'       
  config.vm.define "ubuntu-12.04", autostart: true do |v|
    v.vm.box = "puppetlabs/ubuntu-12.04-64-puppet"
    v.vm.box_version = "1.0.1"
    v.vm.hostname = "ubuntu-12-04"
    v.vm.provision "shell", inline: "sed -i 's/127.0.1.1/127.0.0.1/' /etc/hosts"
    
    # Needed to override to change the default outside-in ordering.
    config.vm.provision "puppet" do |puppet|
      puppet.manifests_path = "manifests"
      puppet.manifest_file  = "site.pp"
      puppet.facter = {
        "boundary_api_token" => ENV["BOUNDARY_API_TOKEN"]     
      }
    end
  end
end

#ubuntu-14.04 Version
if ENV['OSTYPE'] == 'ubuntu-14.04'
    config.vm.define "ubuntu-14.04", autostart: true do |v|
  	config.ssh.insert_key = false
    v.vm.box = "puppetlabs/ubuntu-14.04-64-puppet"
    # fix box_version until Vagrant support newer versions of puppet.
    v.vm.box_version = "1.0.1"
    v.vm.hostname = "ubuntu-14.04"
	#v.vm.provision "shell", inline: "sed -i 's/127.0.1.1/127.0.0.1/' /etc/hosts"
    #v.vm.provider :virtualbox do |vb|
	#	vb.gui = true
	#end 
    # Needed to override to change the default outside-in ordering.
    config.vm.provision "puppet" do |puppet|
      puppet.manifests_path = "manifests"
      puppet.manifest_file  = "site.pp"
      puppet.facter = {
        "boundary_api_token" => ENV["BOUNDARY_API_TOKEN"]
        
      }
    end
  end
end
end
